//
// Created by LENOVO on 11/17/2023.
//

#ifndef CROSSING_ROAD_MESSAGE_H
#define CROSSING_ROAD_MESSAGE_H

enum class Message {
    BLOCK_OUT_OF_SCREEN,
    TRAFFIC_LIGHT_RED,
    TRAFFIC_LIGHT_GREEN,
    COLLISION,
};

#endif //CROSSING_ROAD_MESSAGE_H
